version: '3'
services:

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 127.0.0.1:15432:5432

    volumes:
      - ./postgresdata:/var/lib/postgresql/data

  

  
  
  redis:
    image: redis
    restart: always
    command: [redis-server]
    ports:
      - 127.0.0.1:16379:6379

