site_name="Y3e.cn"
site_title="Create short link- URL Shortener"
site_slogan="Free URL Shortener"
index_keywords="short link, create short url"
index_description="Y3e.cn provides everything you need for URL shortening at scale, including branding and custom domains."


text1="Please enter the url"
text2="Shorten Url"
text3="Recent:"
text4="Copy Success"
text5="Please enter the url"