site_name="Y3e网址缩短"
site_title="短网址服务"
site_slogan="免费快捷网址缩短"
index_keywords="短网址,缩短网址,在线缩短网址,网址压缩,短网址生成"
index_description="Y3e.cn为您提供了大规模缩短URL所需的一切。"

text1="请输入网址"
text2="缩短网址"
text3="最近记录:"
text4="复制成功"